// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI commands (migrate / db pull / studio) use a direct session connection.
    // Supabase: DIRECT_URL is the session-mode pooler on port 5432 (not pgbouncer).
    url: process.env["DIRECT_URL"],
  },
});
